config/routes.rb
Prode::Application.routes.draw do

  resources :bets

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  resources :user_groups
  resources :user_group_members
  resources :teams
  resources :leagues
  resources :matches

  root :to => 'user_groups#index'

  devise_scope :user do
    authenticated :user do
      root :to => 'devise/registrations#edit', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#create', as: :unauthenticated_root
    end
  end
  devise_for :users, :skip => [:sessions, :registrations], :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users

  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to:'devise/sessions#create', as: :user_session
    match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
    get 'cancel', to: 'devise/registrations#cancel', as: :cancel_user_registration
    post 'create' => 'devise/registrations#create', :as => :user_registration
    get 'signup' => 'devise/registrations#new', :as => :new_user_registration
    get 'profile', to: 'devise/registrations#edit', as: :edit_user_registration
    delete 'create', to: 'devise/registrations#destroy'

    patch 'create', to: 'registrations#update'
    put 'create', to: 'registrations#update'
  end

  as :user_groups do
    get 'user_groups/:id/invite_user/:email', to: 'user_groups#invite_user', as: :user_group_invite_user
    get 'user_groups/:id/fixture', to: 'user_groups#fixture', as: :user_group_fixture
  end

  get 'my_groups', to: 'user_groups#index', as: :my_groups

  scope :api do
    get 'user_groups/my_groups', to: 'user_groups#my_groups', defaults: {format: :json}
    get 'user_groups/notifications', to: 'user_groups#notifications', defaults: {format: :json}
    resources :user_groups, defaults: {format: :json}
    post 'user_groups/:id/invite_user', to: 'user_groups#invite_user', defaults: {format: :json}
    post 'user_groups/:id/bet_match', to: 'user_groups#bet_match', defaults: {format: :json}
    get 'user_group_members/:id/my_bets', to: 'user_group_members#my_bets', defaults: {format: :json}
    get 'user_groups/:id/my_bets', to: 'user_groups#my_bets', defaults: {format: :json}
    get 'user_groups/:id/matches/:league_date', to: 'user_groups#matches', defaults: {format: :json}
    post 'user_groups/:id/accept_invitation', to: 'user_groups#accept_invitation', as: :user_group_accept_invitation, defaults: {format: :json}
    post 'user_groups/:id/reject_invitation', to: 'user_groups#reject_invitation', as: :user_group_reject_invitation, defaults: {format: :json}
    resources :matches, defaults: {format: :json}
  end

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base

	validates :user_id, presence: true
	validates :name, presence: true, uniqueness: { case_sensitive: false }
	validates :league_id, presence: true

	has_many :user_group_members
	has_many :users, :through => :user_group_members
	belongs_to :league

	# for the Group owner relationship
	belongs_to :user

end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
	before_action :set_user_group, only: [:show, :edit, :update, :destroy, :invite_user, :fixture, :bet_match, :my_bets, :matches, :reject_invitation, :accept_invitation]

	before_filter :authenticate_user!#, :except => [:some_action_without_auth]

	# GET /user_groups
	# GET /user_groups.json
	def index
		@user_groups = UserGroup.joins(:user_group_members).where("user_group_members.user_id" => current_user.id).all
		@user_group_new = UserGroup.new
		@leagues = League.all
	end

	# GET /user_groups/1
	# GET /user_groups/1.json
	def show
		# scores calculation
		#@todo: hmike: use :score field from db
		@members_scored = @user_group.user_group_members.where(status: 40).sort_by(&:score).reverse!
	end

	# GET /user_groups/new
	def new
		@user_group = UserGroup.new
	end

	# GET /user_groups/1/edit
	def edit
	end

	# POST /user_groups
	# POST /user_groups.json
	def create
		@user_group = UserGroup.new(user_group_params)
		@user_group.user_id = current_user.id

		respond_to do |format|
			if @user_group.save
				@user_group.user_group_members.build(:user_id => current_user.id, status: 40).save
	
				format.html { redirect_to user_groups_path, notice: 'User group was successfully created.' }
				format.json { render action: 'show', status: :created, location: @user_group }
			else
				format.html { render action: 'new' }
				format.json { render json: @user_group.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /user_groups/1
	# PATCH/PUT /user_groups/1.json
	def update
		respond_to do |format|
			if @user_group.update(user_group_params)
				format.html { redirect_to @user_group, notice: 'User group was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @user_group.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /user_groups/1
	# DELETE /user_groups/1.json
	def destroy
		@user_group.destroy
		respond_to do |format|
			format.html { redirect_to user_groups_url }
			format.json { head :no_content }
		end
	end

	def invite_user

		if (current_user.email == params[:email])
			respond_with_errors("No podes invitarte a vos mismo")
			return
		end

		user = User.find_by_email(params[:email])

		if (user)
			# check if the User already are in the group
			@user_group_member = UserGroupMember.where(user_id: user.id , user_group_id: @user_group.id).first

			if (@user_group_member)
				if (@user_group_member.status == 10)
					respond_with_errors("Ya invitaste a este usuario, espera su respuesta")
					return
				elseif (@user_group_member.status == 40)
					respond_with_errors("El usuario ya esta jugando en este grupo")
					return
				end
			end
		else
			# send invitation to new User
			user = User.invite!(:email => params[:email], :name => current_user.email)
		end

		if (!@user_group_member)
			@user_group_member = @user_group.user_group_members.build(:user_id => user.id)
		end

		@user_group_member.status = 10
		# @user_group_members = UserGroupMember.where(user_group_id: @user_group.id)
		
		respond_to do |format|
			if @user_group_member.save
				format.html { redirect_to user_group_members_path, notice: 'El usuario ha sido invitado al grupo!' }
				format.json { render json: build_json_messages('Se invito al usuario al grupo!', 'success'), status: :created }
				# format.json { render 'user_group_members/index', notice: 'El usuario ha sido invitado al grupo!', status: :created }
			else
				format.html { render action: 'new' }
				# format.json { render json: @user_group_member.errors.full_messages, status: :unprocessable_entity }
				format.json { render json: build_json_messages(@user_group_member.errors, 'error'), status: :unprocessable_entity }
			end
		end

		# respond_with_success("Se le envio una invitacion por mail!")
		# return
	end

	def accept_invitation
		user_group_member = UserGroupMember.where(user_id: current_user.id, user_group_id: @user_group.id, status: 10).first
		if (!user_group_member)
			respond_with_errors('Invitacion invalida')
			return
		end

		user_group_member.accept()
		respond_with_success('Te has unido al grupo!')
	end
	
	def reject_invitation
		user_group_member = UserGroupMember.where(user_id: current_user.id, user_group_id: @user_group.id, status: 10).first
		if (!user_group_member)
			respond_with_errors('Invitacion invalida')
			return
		end

		user_group_member.reject()
		respond_with_success('Has rechazado la invitacion')
	end

	def my_groups
		@user_group_members = current_user.user_group_members.where(status: 40)
	end
	
	# GET /user_groups/1/fixture
	# GET /user_groups/1/fixture.json
	def fixture

		# definitions for method compatibility
		@league = @user_group.league
		group_id = @user_group.id

		# @leagues_teams = LeaguesTeams.find_all_by_league_id(@league.id, :order => :group_number)
		@leagues_teams = LeaguesTeams.where(:league => @league).order(:group_number)
		@league_groups = Hash.new
		@leagues_teams.each do |league_team|
			if (!league_team.group_number.nil?) 
				if (!@league_groups[league_team.group_number])
					@league_groups[league_team.group_number] = Array.new
				end
				@league_groups[league_team.group_number].push(league_team)
			end
		end


		@matches = Match.where(:league_id => @league.id, :is_playoff => false).order(:league_date => :asc, :date => :asc)

		# user_group_member = UserGroupMember.joins(:user_group)
		#                                                       .where( :user_id => current_user.id, 
		#                                                               :user_group_id => group_id,
		#                                                               :user_groups => { :league_id => @league.id }
		#                                                             ).first

		user_group_member = @user_group.user_group_members.where(:user_id => current_user.id).first

		# get user bets for group matches
		@user_bets = Hash.new
		@matches.each do |match|
			@user_bets[match.id] = match.bets.where(:match_id => match.id, :user_group_member_id => user_group_member.id).first
		end

		@groups_matches = Hash.new
		@matches.each do |match|
			if (!@groups_matches[match.league_date]) 
				@groups_matches[match.league_date] = Array.new
			end
			@groups_matches[match.league_date].push(match)
		end

		@matches = Match.where(:league_id => @league.id, :is_playoff => true).order(:league_date => :asc, :date => :asc)

		# get user bets for playoff matches
		@matches.each do |match|
			@user_bets[match.id] = match.bets.where(:match_id => match.id, :user_group_member_id => user_group_member.id).first
		end

		@playoff_matches = Hash.new
		@matches.each do |match|
			if (!@playoff_matches[match.league_date]) 
				@playoff_matches[match.league_date] = Array.new
			end
			@playoff_matches[match.league_date].push(match)
		end


		# @todo: hmike: calculate labels based on playoff matches count
		@playoff_labels = Hash.new
		@playoff_labels[4] = 'Octavos'
		@playoff_labels[5] = 'Cuartos'
		@playoff_labels[6] = 'Semifinal'
		@playoff_labels[7] = '3er y 4to Puesto'
		@playoff_labels[8] = 'Final'

	end

	def matches
		@matches = @user_group.league.matches.where(:league_date => params[:league_date]).order(:league_date, :date)
	end

	def bet_match
		#@todo: hmike: validate if the bet was expired
		user_group_member = @user_group.user_group_members.where(:user_id => current_user.id).first
		bet = Bet.where(:user_group_member => user_group_member, :match_id => params[:match_id]).first
		if (bet.nil?)
			bet = Bet.new(:user_group_member => user_group_member, :match_id => params[:match_id])
		end

		if bet.update_attributes(:bet => params[:bet])
			respond_with_success("Apuesta realizada!")
		else
			respond_with_errors("No se pudo realizar la apuesta")
		end
	end

	def my_bets
		user_group_member = @user_group.user_group_members.where(:user_id => current_user.id).first
		@my_bets = Bet.where(:user_group_member => user_group_member)
		@matches = Match.where(:league_id => @user_group.league_id).order(:league_date)
		#sort best by match id
		@bets = Hash.new
		@matches.each do |match|
			@bets[match.id] = match.bets.where(:user_group_member_id => user_group_member.id).first
		end

		respond_to do |format|
			format.html { redirect_to user_group_members_path, notice: 'El usuario ha sido invitado al grupo!' }
			format.json { render 'user_groups/my_bets', notice: 'El usuario ha sido invitado al grupo!', status: :created }
		end
	end

	def notifications
		@notifications = current_user.user_group_members.where(status: 10)
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_user_group
			@user_group = UserGroup.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def user_group_params
			params.require(:user_group).permit(:name, :league_id)
		end

		# respond back to the client an http 200 status plus the message
		def respond_with_success(messages)
			respond_with_messages(messages, 'success', :ok)
			# respond_to do |format|
			#   # render :json => {:errors => errors}, :status => :bad_request
			#   format.html { render notice: message }
			#   format.json { render :json => build_json_errors(message, severity), :status => :ok }
			# end
		end

		# respond back to the client an http 400 status plus the errors array
		def respond_with_errors(errors)
			respond_with_messages(errors, 'error', :bad_request)
			# respond_to do |format|
			#   # render :json => {:errors => errors}, :status => :bad_request
			#   format.html { render notice: errors }
			#   format.json { render :json => build_json_errors(errors, severity), :status => :bad_request }
			# end
		end

		def respond_with_messages(messages, severity, status)
			respond_to do |format|
				format.html { render notice: errors }
				format.json { render :json => build_json_messages(messages, severity), :status => status }
			end
		end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<%= form_for @user_group, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :league_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :league_id, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_groups_path, :class => 'btn' %>
  </div>
<% end %>

app/views/user_groups/edit.html.erb
<%- model_class = UserGroup -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_groups/fixture.html.erb
<div ng-init="init(<%= @user_group.id %>)">

<%- model_class = UserGroup -%>
<div class="page-header">
	<% if (@user_group.league.name == "Torneo Final 2014") %>
		<div class="league-avatar"><%= image_tag ('logos/afa.png') %></div>
	<% else %>
		<div class="league-avatar"><%= image_tag ('logos/fifa_wc2014.png') %></div>
	<% end %>
	<h1><%= @user_group.name %></h1>
	<h3><%= @user_group.league.name %></h3>
</div>

<% 
	if (@user_group.league.name == "Torneo Final 2014")
		base_img = 'afa'
	else
		base_img = 'fifa'
	end
%>

<!-- Show Teams by league date -->
<% @league_groups.each do |k,group_teams| %>
	<table class="table table-hover tbl-standing">
		<caption class="table-title"><%= (k.nil?) ? "" : "Grupo #{k.upcase}" %></caption>
		<thead>
			<tr>
				<th class="col-md-1"></th>
				<th class="col-md-3 tbl-teamname">Nombre</th>
				<th class="col-md-1">PJ</th>
				<th class="col-md-1">PG</th>
				<th class="col-md-1">PP</th>
				<th class="col-md-1">PE</th>
				<th class="col-md-1">GF</th>
				<th class="col-md-1">GC</th>
				<th class="col-md-1">D</th>
				<th class="col-md-1">Pts</th>
			</tr>
		</thead>
		<tbody>
			<% position = 1 %>
			<% group_teams.each do |league_team| %>
				<tr>
					<td><%= position %></td>
					<td class="tbl-teamname tbl-team-<%= league_team.team.code.downcase %>">
						<img src="/assets/teams/<%= base_img %>/<%= league_team.team.code.downcase %>_thumb.png" ></img>
						<label><%= league_team.team.name %></label>
					</td>
					<td><%= league_team.matches_played %></td>
					<td><%= league_team.matches_won %></td>
					<td><%= league_team.matches_lost %></td>
					<td><%= league_team.matches_tied %></td>
					<td><%= league_team.goals_scored %></td>
					<td><%= league_team.goals_against %></td>
					<% diff = (league_team.goals_scored.to_i - league_team.goals_against.to_i) %>
					<td><%= diff %></td>
					<td><%= league_team.points %></td>
				</tr>
				<% position+=1 %>
			<% end %>
		</tbody>
	</table>
<% end %>

<h2>Fixture</h2>

<table class="table tbl-fixture" ng-repeat="(league_date, league_date_matches) in matches" ng-cloak class="ng-cloak">
	<caption class="table-title">Fecha {{league_date+1}}</caption>
	<thead>
		<tr>
			<th class="col-md-1"></th>
			<th class="col-md-2"></th>
			<th class="col-md-3"></th>
			<th class="col-md-3"></th>
			<th class="col-md-3"></th>
		</tr>
	</thead>
	<tbody>
		<tr ng-repeat="match in league_date_matches">
			<td class="tbl-date">
				<span>{{match.date | date: 'EEE d MMM.'}}</span>
				<span>{{match.date | date: 'yyyy'}}</span>
				<span class="bold">Fecha {{match.league_date}}</span>
			</td>
			<!-- <td class="tbl-score">{{match.date.strftime("%k:%M")}}</td> -->
			<td class="tbl-score">
				<div ng-class="{'hide' : (match.is_expired)}">
					{{match.date | date: 'HH:mm'}}
				</div>
				<div class="bet-score" ng-class="{'hide' : (!match.is_expired), 'win' : (my_bets[match.id].bet.win)}">
					<span>+{{{true: my_bets[match.id].bet.score, false: 0}[my_bets[match.id].bet != null]}}</span>
					<p>{{{true: my_bets[match.id].bet.bet_label, false: '-'}[my_bets[match.id].bet != null]}}</p>
				</div>
			</td>
			<td class="tbl-teamname tbl-teamlocal tbl-team-{{match.local_team.team.code | lowercase}}">
				<div ng-class="{'hide' : (match.is_expired)}">
					<button class="btn-press" ng-class="{'active' : (my_bets[match.id].bet.bet==1)}" ng-model="my_bets[match.id].bet.bet" value="1" ng-click='betMatch(<%= @user_group.id %>, match.id, 1)'>
						<img ng-src="/assets/teams/<%= base_img %>/{{match.local_team.team.code | lowercase}}_medium.png" ></img>
						<label>{{match.local_team.team.name}}</label>
					</button>
				</div>
				<div class="text-center" ng-class="{'hide' : (!match.is_expired)}">
					<img ng-src="/assets/teams/<%= base_img %>/{{match.local_team.team.code | lowercase}}_medium.png" ></img>
					<label>{{match.local_team.team.name}}</label>
				</div>
			</td>
			<td class="tbl-tied">
				<div ng-class="{'hide' : (match.is_expired)}">
					<button class="btn-press" ng-class="{'active' : (my_bets[match.id].bet.bet==0)}" ng-model="my_bets[match.id].bet.bet" value="0" ng-click='betMatch(<%= @user_group.id %>, match.id, 0)'>
						<label>EMPATE<label>
					</button>
				</div>
				<div ng-class="{'hide' : (!match.is_expired)}">
					<label>
						{{{true: match.local_score, false: 0}[match.local_score != nill]}}
						-
						{{{true: match.away_score, false: 0}[match.away_score != nill]}}
					</label>
					<!-- <label>{{match.local_score}} - {{match.away_score}}<label> -->
				</div>
			</td>
			<td class="tbl-teamname tbl-teamaway tbl-team-{{match.away_team.team.code | lowercase}}">
				<div ng-class="{'hide' : (match.is_expired)}">
					<button class="btn-press" ng-class="{'active' : (my_bets[match.id].bet.bet==2)}" ng-model="my_bets[match.id].bet.bet" value="2" ng-click='betMatch(<%= @user_group.id %>, match.id, 2)'>
						<img ng-src="/assets/teams/<%= base_img %>/{{match.away_team.team.code | lowercase}}_thumb.png" ></img>
						<label>{{match.away_team.team.name}}</label>
					</button>
				</div>
				<div class="text-center" ng-class="{'hide' : (!match.is_expired)}">
					<label>{{match.away_team.team.name}}</label>
					<img ng-src="/assets/teams/<%= base_img %>/{{match.away_team.team.code | lowercase}}_thumb.png" ></img>
				</div>
			</td>
		</tr>
	</tbody>
</table>

app/views/user_groups/index.html.erb
<%- model_class = UserGroup -%>
<div class="page-header">
	<h1>Mis Grupos</h1>
</div>

<div ng-cloak class="ng-cloak">
	<!-- <form ng-submit="createUserGroup()" class="col-md-4">
		<div class="input-group">
		<input type="text" class="form-control" placeholder="Nuevo grupo" ng-model="newName">
		<span class="input-group-btn">
			<button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i></button>
		</span>
		</div>
		<div class="input-group">
		<select class="form-control" ng-model="newLeague" ng-init="newLeague = <%= @leagues.first.id %>">
		<% @leagues.each do |league| %>
			<option value="<%= league.id %>"><%= league.name %></option>
		<% end %>
		</select>
		</div>
	</form> -->
	<!-- <form ng-submit="searchUserGroup()" class="col-md-4">
		<div class="input-group">
		<input type="text" class="form-control" placeholder="Buscar..." ng-model='searchName'>
		<span class="input-group-btn">
			<button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
		</span>
		</div>
	</form> -->
<!--   <input type="text" ng-model='newName' placeholder="Nuevo nombre">
	<input type="submit" value="Crear">
<form ng-submit="searchUserGroup()">
	<input type="text" ng-model='searchName' placeholder="Buscar...">
	<input type="submit" value="Buscar">
</form> -->
	<table class="table table-hover tbl-groups">
		<!-- <caption class="table-title"><%= "Grupo " %></caption> -->
		<thead>
			<tr>
				<!-- <th class="col-md-3">Nombre</th>
				<th class="col-md-7">Miembros</th> -->
				<!-- <th><%=t '.actions', :default => t("helpers.actions") %></th> -->
				<!-- <th class="col-md-2"></th> -->
				<th class="col-md-10"></th>
				<th class="col-md-2"></th>
			</tr>
		</thead>
		<tbody>
			<tr class="row-group" ng-repeat="user_group in user_groups | filter: {name: searchName }">
			<!-- <td><%= link_to "{{user_group.id}}", "user_groups/{{user_group.id}}" %></td> -->
			<!-- <td>{{user_group.user.email}}</td> -->
				<td>
					<div class="group-name">{{user_group.name}}</div>
					<div class="group-league"><img ng-src="{{user_group.league.avatar_thumb_url}}" />{{user_group.league.name}}</div>
				</td>
				<!-- <td>{{user_group.members}}</td> -->
				<!-- <td>
					<div class="groupMembers">
					<span ng-repeat="member in user_group.members">
						<!-- {{member.email}}<br/> ->
						{{member.user.email}}<br/>
					</span>
					</div>
					<form ng-submit="inviteUser(user_group.id, $index)" class="col-md-6">
					<div class="input-group">
						<input type="text" class="form-control" placeholder="Ingresa el email de quien quieras invitar" ng-model='user_groups[$index].newMemberEmail'>
						<span class="input-group-btn">
							<button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i></button>
						</span>
					</div>
					</form>
				</td> -->
				<td class="tbl-group-links">
					<%= #link_to "Ver Grupo", "user_groups/{{user_group.id}}", :class => 'btn btn-mini' 
					%>
					<!-- <a href='' class="btn btn-mini btn-danger" ng-click="deleteUserGroup(user_group.id, $index)">Borrar</a> -->
					<a ng-href='user_groups/{{user_group.id}}' class="">
						<i class='fa fa-angle-right'></i>
					</a>
					<!--<%= link_to "<i class='fa fa-angle-right'></i>".html_safe, "user_groups/{{user_group.id}}", :class => '' %>-->
				</td>
			</tr>
		</tbody>
	</table>
</div>

app/views/user_groups/new.html.erb
<%- model_class = UserGroup -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_groups/show.html.erb
<div ng-controller="UserGroupsCtrl" ng-init="init(<%= @user_group.id %>)">
<div class="page-header">
	<% if (@user_group.league.name == "Torneo Final 2014") %>
		<div class="league-avatar"><%= image_tag ('logos/afa.png') %></div>
	<% else %>
		<div class="league-avatar"><%= image_tag ('logos/fifa_wc2014.png') %></div>
	<% end %>
	<h1><%= @user_group.name %></h1>
	<h3><%= @user_group.league.name %></h3>
</div>
<% if (current_user.can_manage_group(@user_group)) %>
<form ng-submit="inviteUser(current_group.id, null)" class="col-md-6 invite-user">
	<div class="input-group">
		<input type="email" class="form-control" placeholder="Ingresa el email de quien quieras invitar" ng-model='newMemberEmail' required="required">
		<span class="input-group-btn">
			<button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i></button>
		</span>
	</div>
</form>
<% end %>
<div class="form-actions">
	<%= #link_to t('.back', :default => t("helpers.links.back")),
		#					user_groups_path, :class => 'btn btn-primary'
	%>
	<%= link_to "ver fixture<i class='fa fa-angle-right'></i>".html_safe, user_group_fixture_path, :class => '' %>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th class="col-md-1"></th>
			<th class="col-md-9">Nombre</th>
			<th class="col-md-1 text-center">Pts</th>
			<th class="col-md-1 text-center">%</th>
		</tr>
	</thead>
	<tbody>
		<% position = 1 %>
		<% @members_scored.each do |member| %>
			<tr>
				<td><%= position %></td>
				<td>
					<%= image_tag member.user.avatar(:thumb), :class => 'img img-thumb' %>
					<%= member.user.email %>
				</td>
				<td class="text-center"><%= member.score %></td>
				<td class="text-center">-</td>
			</tr>
			<% position+=1 %>
		<% end %>
	</tbody>
</table>
</div>