config/routes.rb
Prode::Application.routes.draw do

  resources :bets

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  resources :user_groups
  resources :user_group_members
  resources :teams
  resources :leagues
  resources :matches

  root :to => 'user_groups#index'

  devise_scope :user do
    authenticated :user do
      root :to => 'devise/registrations#edit', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#create', as: :unauthenticated_root
    end
  end
  devise_for :users, :skip => [:sessions, :registrations], :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users

  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to:'devise/sessions#create', as: :user_session
    match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
    get 'cancel', to: 'devise/registrations#cancel', as: :cancel_user_registration
    post 'create' => 'devise/registrations#create', :as => :user_registration
    get 'signup' => 'devise/registrations#new', :as => :new_user_registration
    get 'profile', to: 'devise/registrations#edit', as: :edit_user_registration
    delete 'create', to: 'devise/registrations#destroy'

    patch 'create', to: 'registrations#update'
    put 'create', to: 'registrations#update'
  end

  as :user_groups do
    get 'user_groups/:id/invite_user/:email', to: 'user_groups#invite_user', as: :user_group_invite_user
    get 'user_groups/:id/fixture', to: 'user_groups#fixture', as: :user_group_fixture
  end

  get 'my_groups', to: 'user_groups#index', as: :my_groups

  scope :api do
    get 'user_groups/my_groups', to: 'user_groups#my_groups', defaults: {format: :json}
    get 'user_groups/notifications', to: 'user_groups#notifications', defaults: {format: :json}
    resources :user_groups, defaults: {format: :json}
    post 'user_groups/:id/invite_user', to: 'user_groups#invite_user', defaults: {format: :json}
    post 'user_groups/:id/bet_match', to: 'user_groups#bet_match', defaults: {format: :json}
    get 'user_group_members/:id/my_bets', to: 'user_group_members#my_bets', defaults: {format: :json}
    get 'user_groups/:id/my_bets', to: 'user_groups#my_bets', defaults: {format: :json}
    get 'user_groups/:id/matches/:league_date', to: 'user_groups#matches', defaults: {format: :json}
    post 'user_groups/:id/accept_invitation', to: 'user_groups#accept_invitation', as: :user_group_accept_invitation, defaults: {format: :json}
    post 'user_groups/:id/reject_invitation', to: 'user_groups#reject_invitation', as: :user_group_reject_invitation, defaults: {format: :json}
    resources :matches, defaults: {format: :json}
  end

end

app/models/bet.rb
class Bet < ActiveRecord::Base

	validates :user_group_member_id, presence: true
	validates :match_id, presence: true
	# validates :bet, presence: true

	belongs_to :user_group_member
	belongs_to :match

	def win
		bet_win = false
		if match.is_local_win
			bet_win = (bet == 1)
		elsif match.is_away_win
			bet_win = (bet == 2)
		elsif match.is_tie
			bet_win = (bet == 0)
		end
		return bet_win
	end

	def score
		win ? 1:0
	end

	def bet_label
		case bet
		when 0
			'empate'
		when 1
			'local'
		when 2
			'visitante'
		end
	end

end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :set_bet, only: [:show, :edit, :update, :destroy]

  # GET /bets
  # GET /bets.json
  def index
    @bets = Bet.all
  end

  # GET /bets/1
  # GET /bets/1.json
  def show
  end

  # GET /bets/new
  def new
    @bet = Bet.new
  end

  # GET /bets/1/edit
  def edit
  end

  # POST /bets
  # POST /bets.json
  def create
    @bet = Bet.new(bet_params)

    respond_to do |format|
      if @bet.save
        format.html { redirect_to @bet, notice: 'Bet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bet }
      else
        format.html { render action: 'new' }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bets/1
  # PATCH/PUT /bets/1.json
  def update
    respond_to do |format|
      if @bet.update(bet_params)
        format.html { redirect_to @bet, notice: 'Bet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bets/1
  # DELETE /bets/1.json
  def destroy
    @bet.destroy
    respond_to do |format|
      format.html { redirect_to bets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bet
      @bet = Bet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bet_params
      params.require(:bet).permit(:user_group_member_id, :match_id, :bet)
    end
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_form.html.erb
<%= form_for(@bet) do |f| %>
  <% if @bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% @bet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_group_member_id %><br>
    <%= f.number_field :user_group_member_id %>
  </div>
  <div class="field">
    <%= f.label :match_id %><br>
    <%= f.number_field :match_id %>
  </div>
  <div class="field">
    <%= f.label :bet %><br>
    <%= f.number_field :bet %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bets/edit.html.erb
<h1>Editing bet</h1>

<%= render 'form' %>

<%= link_to 'Show', @bet %> |
<%= link_to 'Back', bets_path %>

app/views/bets/index.html.erb
<h1>Listing bets</h1>

<table>
  <thead>
    <tr>
      <th>User group member</th>
      <th>Match</th>
      <th>Bet</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bets.each do |bet| %>
      <tr>
        <td><%= bet.user_group_member_id %></td>
        <td><%= bet.match_id %></td>
        <td><%= bet.bet %></td>
        <td><%= link_to 'Show', bet %></td>
        <td><%= link_to 'Edit', edit_bet_path(bet) %></td>
        <td><%= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bet', new_bet_path %>

app/views/bets/new.html.erb
<h1>New bet</h1>

<%= render 'form' %>

<%= link_to 'Back', bets_path %>

app/views/bets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User group member:</strong>
  <%= @bet.user_group_member_id %>
</p>

<p>
  <strong>Match:</strong>
  <%= @bet.match_id %>
</p>

<p>
  <strong>Bet:</strong>
  <%= @bet.bet %>
</p>

<%= link_to 'Edit', edit_bet_path(@bet) %> |
<%= link_to 'Back', bets_path %>