config/routes.rb
Prode::Application.routes.draw do

  resources :bets

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  resources :user_groups
  resources :user_group_members
  resources :teams
  resources :leagues
  resources :matches

  root :to => 'user_groups#index'

  devise_scope :user do
    authenticated :user do
      root :to => 'devise/registrations#edit', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#create', as: :unauthenticated_root
    end
  end
  devise_for :users, :skip => [:sessions, :registrations], :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users

  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to:'devise/sessions#create', as: :user_session
    match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
    get 'cancel', to: 'devise/registrations#cancel', as: :cancel_user_registration
    post 'create' => 'devise/registrations#create', :as => :user_registration
    get 'signup' => 'devise/registrations#new', :as => :new_user_registration
    get 'profile', to: 'devise/registrations#edit', as: :edit_user_registration
    delete 'create', to: 'devise/registrations#destroy'

    patch 'create', to: 'registrations#update'
    put 'create', to: 'registrations#update'
  end

  as :user_groups do
    get 'user_groups/:id/invite_user/:email', to: 'user_groups#invite_user', as: :user_group_invite_user
    get 'user_groups/:id/fixture', to: 'user_groups#fixture', as: :user_group_fixture
  end

  get 'my_groups', to: 'user_groups#index', as: :my_groups

  scope :api do
    get 'user_groups/my_groups', to: 'user_groups#my_groups', defaults: {format: :json}
    get 'user_groups/notifications', to: 'user_groups#notifications', defaults: {format: :json}
    resources :user_groups, defaults: {format: :json}
    post 'user_groups/:id/invite_user', to: 'user_groups#invite_user', defaults: {format: :json}
    post 'user_groups/:id/bet_match', to: 'user_groups#bet_match', defaults: {format: :json}
    get 'user_group_members/:id/my_bets', to: 'user_group_members#my_bets', defaults: {format: :json}
    get 'user_groups/:id/my_bets', to: 'user_groups#my_bets', defaults: {format: :json}
    get 'user_groups/:id/matches/:league_date', to: 'user_groups#matches', defaults: {format: :json}
    post 'user_groups/:id/accept_invitation', to: 'user_groups#accept_invitation', as: :user_group_accept_invitation, defaults: {format: :json}
    post 'user_groups/:id/reject_invitation', to: 'user_groups#reject_invitation', as: :user_group_reject_invitation, defaults: {format: :json}
    resources :matches, defaults: {format: :json}
  end

end

app/models/match.rb
class Match < ActiveRecord::Base

	validates :league_id, presence: true
	validates :date, presence: true
	validates :local_team_id, presence: true
	validates :away_team_id, presence: true
	#validates :local_score, presence: true, :numericality => { :only_integer => true }
	#validates :away_score, presence: true, :numericality => { :only_integer => true }
	validates :league_date, presence: true, :numericality => { :only_integer => true }
	#validates :is_playoff, presence: true

	belongs_to :league
	belongs_to :local_team, :class_name => 'Team'
	belongs_to :away_team, :class_name => 'Team'
	has_many :bets

	def was_played
		(local_score != nil && away_score != nil)
	end

	def is_local_win
		#@todo: hmike: handle this error case
		if !was_played
			return nil
		end

		(local_score > away_score)
	end

	def is_away_win
		#@todo: hmike: handle this error case
		if !was_played
			return nil
		end

		(local_score < away_score)
	end

	def is_tie
		#@todo: hmike: handle this error case
		if !was_played
			return nil
		end

		(local_score == away_score)
	end

	def is_expired
		date.past?
		# (Time.now - self.date).hours < 2.hours
		# date.to_datetime.to_s
		# (DateTime.now - date)
		# (date - DateTime.now) < 2.hours
		# 2.hours
		# DateTime.now
		# date
	end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render action: 'show', status: :created, location: @match }
      else
        format.html { render action: 'new' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:league_id, :date, :local_team_id, :away_team_id, :local_score, :away_score, :league_date)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for @match, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :league_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :league_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :date, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :local_team_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :local_team_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :away_team_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :away_team_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :local_score, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :local_score, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :away_score, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :away_score, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :league_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :league_date, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                matches_path, :class => 'btn' %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<%- model_class = Match -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/matches/index.html.erb
<%- model_class = Match -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:league_id) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:local_team_id) %></th>
      <th><%= model_class.human_attribute_name(:away_team_id) %></th>
      <th><%= model_class.human_attribute_name(:local_score) %></th>
      <th><%= model_class.human_attribute_name(:away_score) %></th>
      <th><%= model_class.human_attribute_name(:league_date) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= link_to match.id, match_path(match) %></td>
        <td><%= match.league_id %></td>
        <td><%= match.date %></td>
        <td><%= match.local_team_id %></td>
        <td><%= match.away_team_id %></td>
        <td><%= match.local_score %></td>
        <td><%= match.away_score %></td>
        <td><%= match.league_date %></td>
        <td><%=l match.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_match_path(match), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      match_path(match),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_match_path,
            :class => 'btn btn-primary' %>

app/views/matches/new.html.erb
<%- model_class = Match -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/matches/show.html.erb
<%- model_class = Match -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:league_id) %>:</strong></dt>
  <dd><%= @match.league_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @match.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:local_team_id) %>:</strong></dt>
  <dd><%= @match.local_team_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:away_team_id) %>:</strong></dt>
  <dd><%= @match.away_team_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:local_score) %>:</strong></dt>
  <dd><%= @match.local_score %></dd>
  <dt><strong><%= model_class.human_attribute_name(:away_score) %>:</strong></dt>
  <dd><%= @match.away_score %></dd>
  <dt><strong><%= model_class.human_attribute_name(:league_date) %>:</strong></dt>
  <dd><%= @match.league_date %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              matches_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_match_path(@match), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              match_path(@match),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>