config/routes.rb
Prode::Application.routes.draw do

  resources :bets

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  resources :user_groups
  resources :user_group_members
  resources :teams
  resources :leagues
  resources :matches

  root :to => 'user_groups#index'

  devise_scope :user do
    authenticated :user do
      root :to => 'devise/registrations#edit', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#create', as: :unauthenticated_root
    end
  end
  devise_for :users, :skip => [:sessions, :registrations], :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users

  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to:'devise/sessions#create', as: :user_session
    match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
    get 'cancel', to: 'devise/registrations#cancel', as: :cancel_user_registration
    post 'create' => 'devise/registrations#create', :as => :user_registration
    get 'signup' => 'devise/registrations#new', :as => :new_user_registration
    get 'profile', to: 'devise/registrations#edit', as: :edit_user_registration
    delete 'create', to: 'devise/registrations#destroy'

    patch 'create', to: 'registrations#update'
    put 'create', to: 'registrations#update'
  end

  as :user_groups do
    get 'user_groups/:id/invite_user/:email', to: 'user_groups#invite_user', as: :user_group_invite_user
    get 'user_groups/:id/fixture', to: 'user_groups#fixture', as: :user_group_fixture
  end

  get 'my_groups', to: 'user_groups#index', as: :my_groups

  scope :api do
    get 'user_groups/my_groups', to: 'user_groups#my_groups', defaults: {format: :json}
    get 'user_groups/notifications', to: 'user_groups#notifications', defaults: {format: :json}
    resources :user_groups, defaults: {format: :json}
    post 'user_groups/:id/invite_user', to: 'user_groups#invite_user', defaults: {format: :json}
    post 'user_groups/:id/bet_match', to: 'user_groups#bet_match', defaults: {format: :json}
    get 'user_group_members/:id/my_bets', to: 'user_group_members#my_bets', defaults: {format: :json}
    get 'user_groups/:id/my_bets', to: 'user_groups#my_bets', defaults: {format: :json}
    get 'user_groups/:id/matches/:league_date', to: 'user_groups#matches', defaults: {format: :json}
    post 'user_groups/:id/accept_invitation', to: 'user_groups#accept_invitation', as: :user_group_accept_invitation, defaults: {format: :json}
    post 'user_groups/:id/reject_invitation', to: 'user_groups#reject_invitation', as: :user_group_reject_invitation, defaults: {format: :json}
    resources :matches, defaults: {format: :json}
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Prode" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <% if current_page?(authenticated_root_path) %>
            <!-- <a class="navbar-brand" href="#">PROde online.</a> -->
            <a class="brand" href="#">PROde</a>
          <% else %>
            <%= link_to "PROde", authenticated_root_path, :class => "brand" %>
          <% end %>
          <div class="container nav-collapse">
            <ul class="nav navbar-nav navbar-left">
            <% if user_signed_in? %>
              <li class=""><%= link_to "Grupos", user_groups_path %></li>
              <li class=""><%= link_to "Torneos", leagues_path %></li>
              <% if current_user.admin? %>
                <li class=""><%= link_to "Admin", rails_admin_path %></li>
              <% end %>
            <% else %>
              <li><%= link_to "Entrar", new_user_session_path %></li>
              <li><%= link_to "Registrarse", new_user_registration_path %></li>
            <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="cart"><%= link_to "", user_groups_path %></li>
              <li class="en"><%= link_to "", leagues_path %></li>
              <li class="search"><%= link_to "", leagues_path %></li>
              <li class="user"><a href="#" onclick="showSubNavBar()"></a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <script type="text/javascript">
      function showSubNavBar(submenu){
        $('.subnavbar').toggle();
        $('.' + submenu).show();
      }

      function hideSubNavBar(){
        $('.subnavbar').hide();
      }
    </script>

    <div class="navbar navbar-fixed-top subnavbar hide">
      <div class="container">
        <a class="close" href='#' onclick="hideSubNavBar()">
        </a>
        <div class="profile-left">
          <% if !user_signed_in? %>
            <div class="title">

            </div>
            <div>
              <p>Todavía no te registraste? Que estas esperando?</p>
              <%= link_to "REGISTRARSE", new_user_registration_path, :class => 'btn btn-primary' %><br />
            </div>
          <% else %>  
          <% end %>
        </div>
        <div class="profile-right">
          <% if !user_signed_in? %>
            <div class="title">Inicio de sesión</div>
            <div class="login-container">
              <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
                <div class="form-group"><%= f.email_field :email, :autofocus => true, :placeholder => 'email' %></div>
                <div class="form-group"><%= f.password_field :password, :placeholder => 'password' %></div>
                <div class="form-group"><a href="#">Si has olvidado tu contraseña...</a></div>
                <% if devise_mapping.rememberable? %>
                  <div><%= f.check_box :remember_me %><%= f.label :remember_me, :class => 'remember-me' %></div>
                <% end %>
                <div class="form-group"><%= f.submit "Iniciar sesión", :class => 'btn btn-primary right login-btn' %></div>
              <% end %>

            </div>
            <div class="login-social">
              <%= link_to "<i class='fa fa-facebook-square'></i><span>Iniciar sesión con Facebook</span>".html_safe, omniauth_authorize_path(resource_name, 'facebook'), :class => 'btn btn-facebook' %>
              <%= link_to "<i class='fa fa-google-plus-square'></i><span>Iniciar sesión con Google</span>".html_safe, omniauth_authorize_path(resource_name, 'google_oauth2'), :class => 'btn btn-google-plus' %>
            </div>
          <% else %>
              <div class="title">Tu perfil</div>
              <div class="logged-container">
                <div class="form-group">
                  <%= link_to edit_user_registration_path do  %>
                    <%= image_tag current_user.avatar(:medium), :class => 'avatar' %>
                  <% end %>
                  <span>
                    <h2><%= current_user.name %></h2>
                    <%= link_to "edit<i class='fa fa-angle-right'></i>".html_safe, edit_user_registration_path, :class => 'edit' %>
                  </span>
                </div>
              </div>
              <div class="logged-logout">
                <%= link_to "Desconectar", destroy_user_session_path, :method => :delete, :class => 'btn btn-primary logout-btn' %>
              </div>
          <% end %>
        </div>
      </div>
    </div>

    <div growl class="growlMessages"></div>
    <div class="container main-container">
      <!-- <%= bootstrap_flash %> -->
      <%= yield %>
    </div> <!-- /container -->

      <!-- <footer class="navbar-fixed-bottom">
        <div class="container">
          <p>Copyright&copy; 2014 PRODE. Reservados todos los derechos</p>
        </div>
      </footer> -->

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/default.html.erb
<!DOCTYPE html>
<html lang="en" ng-app='Prode' ng-controller="UserGroupsCtrl">
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><%= content_for?(:title) ? yield(:title) : "Prode" %></title>
	<%= csrf_meta_tags %>

	<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
	<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
	<![endif]-->

	<%= stylesheet_link_tag "default", :media => "all" %>
	
	<!-- For third-generation iPad with high-resolution Retina display: -->
	<!-- Size should be 144 x 144 pixels -->
	<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

	<!-- For iPhone with high-resolution Retina display: -->
	<!-- Size should be 114 x 114 pixels -->
	<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

	<!-- For first- and second-generation iPad: -->
	<!-- Size should be 72 x 72 pixels -->
	<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

	<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
	<!-- Size should be 57 x 57 pixels -->
	<%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

	<!-- For all other devices -->
	<!-- Size should be 32 x 32 pixels -->
	<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
	</head>
	<body>

	<!-- Fixed navbar -->
	<div class="navbar navbar navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				</button>
				<% if current_page?(authenticated_root_path) %>
				<a class="navbar-brand" href="#">PROde<i class='fa fa-star'></i></a>
				<% else %>
				<%= link_to "PROde<i class='fa fa-star'></i>".html_safe, authenticated_root_path, :class => "navbar-brand" %>
				<% end %>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
						<% if current_user.admin? %>
						<li class=""><%= link_to "<i class='fa fa-cogs'>".html_safe, rails_admin_path, :target => '_blank' %></i></a></li>
						<% end %>
						<li class="trophy"><a href="#" onclick="return toggleSubnavbarMenu('subnavbar-trophy')"><i class='fa fa-trophy'></i></a></li>
						<li class="groups"><a href="#" onclick="return toggleSubnavbarMenu('subnavbar-groups')"><i class='fa fa-users'></i></a></li>
					<% end %>
					<li class="user"><a href="#" onclick="return toggleSubnavbarMenu('subnavbar-user')">
						<i class='fa fa-user'>
							<% if (user_signed_in?) %>
								<span class="badge ng-cloak" ng-cloak ng-show="notifications.length">{{notifications.length}}</span>
							<% end %>
						</i>
					</a></li>
				</ul>
			</div>
		</div>
	</div>

	<div class="navbar navbar-fixed-top subnavbar">
		<div class="container">

			<!-- subnavbar-user -->
			<div class="subnavbar-panel subnavbar-user">
				<a class="close" href='#' onclick="return hideAllSubnavbarMenus()">x</a>
				<div class="panel-left">
				<% if !user_signed_in? %>
					<div class="title">

					</div>
					<div>
					<p>Todavía no te registraste?</p>
					</p>Registrate y empezá a jugar ya!</p>
					<%= link_to "REGISTRARSE", new_user_registration_path, :class => 'btn btn-primary' %><br />
					</div>
				<% elsif current_user.user_group_members.where(status: 10).count > 0 %>
					<div class="title">
						Notificaciones
					</div>
					<div class="notifications-container">
						<div class="notification ng-cloak" ng-cloak ng-repeat="user_group_member in notifications">
							<a ng-href='/user_groups/{{user_group_member.user_group.id}}' class="">
								<img class="avatar" ng-src="/assets/logos/fifa_wc2014.png" />
								Invitación del grupo <span>{{user_group_member.user_group.name}}</span>
							</a>
							<button class="reject" ng-click="rejectInvitation(user_group_member.user_group.id)"><i class='fa'>x</i></button>
							<button class="accept" ng-click="acceptInvitation(user_group_member.user_group.id)"><i class='fa fa-check'></i></button>
						</div>
					</div>
				<% end %>
				</div>
				<div class="panel-right">
				<% if !user_signed_in? %>
					<div class="title">Inicio de sesión</div>
					<div class="login-container">
					<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
						<div class="form-group"><%= f.email_field :email, :autofocus => true, :placeholder => 'email' %></div>
						<div class="form-group"><%= f.password_field :password, :placeholder => 'contraseña' %></div>
						<!-- <div class="form-group"><a href="#">Si has olvidado tu contraseña...</a></div> -->
						<div class="form-group label label-error"><%= devise_error_messages! %></div>
						<!--<% if devise_mapping.rememberable? %>
						<div><%= f.check_box :remember_me %><%= f.label :remember_me, :class => 'remember-me' %></div>
						<% end %>-->
						<div class="form-group"><%= f.submit "Iniciar sesión", :class => 'btn btn-primary right login-btn' %></div>
					<% end %>

					</div>
					<div class="login-social">
					<%= link_to "<i class='fa fa-facebook-square'></i><span>Iniciar sesión con Facebook</span>".html_safe, omniauth_authorize_path(resource_name, 'facebook'), :class => 'btn btn-social btn-facebook' %>
					<%= link_to "<i class='fa fa-google-plus-square'></i><span>Iniciar sesión con Google</span>".html_safe, omniauth_authorize_path(resource_name, 'google_oauth2'), :class => 'btn btn-social btn-google-plus' %>
					</div>
				<% else %>
					<div class="title">Tu perfil</div>
					<div class="logged-container">
					<div class="form-group">
						<%= link_to edit_user_registration_path do  %>
						<%= image_tag current_user.avatar(:medium), :class => 'avatar' %>
						<% end %>
						<span>
						<h2 id="logged-username"><%= current_user.name %></h2>
						<%= link_to "edit<i class='fa fa-angle-right'></i>".html_safe, edit_user_registration_path, :class => 'edit' %>
						</span>
					</div>

					</div>
					<div class="logged-logout">
					<%= link_to "Desconectar", destroy_user_session_path, :method => :delete, :class => 'btn btn-primary logout-btn' %>
					</div>
				<% end %>
				</div>
			</div>
			<!-- end subnavbar-user -->

			<!-- subnavbar-groups -->
			<div class="subnavbar-panel subnavbar-groups">
				<% if user_signed_in? %>
				<a class="close" href='#' onclick="return hideAllSubnavbarMenus()">x</a>
				<div class="panel-left">
					<div class="title">
					Mis Grupos
					</div>
					<div class="groups-container">
						<div ng-show="!user_groups.length">
							<h4>Todavia no tenes grupo? <br>Creá uno, invitá a tus amigos y empezá a jugar!!!</h4>
							<p>También podés recibir invitaciones para jugar en los grupos de tus amigos, chequeá tus notificationes para unirte y jugar con ellos.</p>
						</div>
						<div class="group-container ng-cloak" ng-cloak ng-repeat="user_group in user_groups">
							<a ng-href='/user_groups/{{user_group.id}}' class="">
								<img class="avatar" ng-src="{{user_group.league.avatar_thumb_url}}" />
								<span>{{user_group.name}}</span>
							</a>
						</div>
						<!--<% current_user.user_group_members.where(status: 40).reverse.first(3).each do |user_group_member| %>
							<div class="group-container">
							<%= link_to user_group_member.user_group do %>
								<%= image_tag user_group_member.user_group.league.avatar(:thumb), :class => 'avatar' %>
								<span><%= user_group_member.user_group.name %></span>
							<% end %>
							</div>
						<% end %>-->
						<div class="group-more">
							<%= link_to 'ver grupos<i class="fa fa-angle-right"></i>'.html_safe, my_groups_path %>
						</div>
					</div>
				</div>
				<div class="panel-right">
					<div class="title">Crear nuevo grupo</div>
					<%= form_for(current_user.user_groups.new) do |f| %>
					<div class="form-group"><%= f.text_field :name, :autofocus => true, :placeholder => 'Nombre del grupo', :maxlength => 40 %></div>
					<div class="form-group">
						<%= f.select(:league_id, options_from_collection_for_select(current_leagues, :id, :name), :class => 'form-control') %>
					</div>
					<div class="form-group"><%= f.submit "Crear", :class => 'btn btn-primary right' %></div>
					<% end %>
				</div>
				<% end %>
			</div>
			<!-- end subnavbar-trophy -->

			<!-- subnavbar-trophy -->
			<div class="subnavbar-panel subnavbar-trophy">
				<a class="close" href='#' onclick="return hideAllSubnavbarMenus()">x</a>
			</div>
			<!-- end subnavbar-trophy -->

		</div><!-- end container -->
	</div><!-- end subnavbar -->

	<div growl class="growlMessages"></div>
	<div class="container main-container">
		<%= yield %>
	</div><!-- end container -->

		<!-- <footer class="navbar-fixed-bottom">
		<div class="container">
			<p>Copyright&copy; 2014 PRODE. Reservados todos los derechos</p>
		</div>
		</footer> -->

	<!-- Javascripts -->
	<!-- Placed at the end of the document so the pages load faster -->
	<%= javascript_include_tag "default" %>
	<%= yield(:page_javascript) if content_for?(:page_javascript) %>

	</body>
</html>

app/views/layouts/default_mine.html.erb
<!DOCTYPE html>
<html lang="en" ng-app='Prode'>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PROde online." %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "default", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle " data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if current_page?(authenticated_root_path) %>
            <a class="navbar-brand" href="#">PROde online.</a>
          <% else %>
            <%= link_to "PROde online.", authenticated_root_path, :class => "navbar-brand" %>
          <% end %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li class="">
              <%= link_to edit_user_registration_path do  %>
              <%= image_tag (current_user.avatar(:thumb)) %>
              <% end %>
            </li>
            <li class=""><%= link_to "Grupos", user_groups_path %></li>
            <li class=""><%= link_to "Torneos", leagues_path %></li>
            <li class=""><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
            <% if current_user.admin? %>
              <li class=""><%= link_to "Admin", rails_admin_path %></li>
            <% end %>
          <% else %>
            <li><%= link_to "Entrar", new_user_session_path %></li>
            <li><%= link_to "Registrarse", new_user_registration_path %></li>
          <% end %>
            <!-- <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div growl class="growlMessages"></div>
    <div class="container theme-showcase">

      <%= yield %>

    </div> <!-- /container -->

    <!-- Javascripts -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "yeti" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>

app/views/layouts/yeti.html.erb
<!DOCTYPE html>
<html lang="en" ng-app='Prode'>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PROde online." %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "yeti", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle " data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if current_page?(authenticated_root_path) %>
            <a class="navbar-brand" href="#">PROde online.</a>
          <% else %>
            <%= link_to "PROde online.", authenticated_root_path, :class => "navbar-brand" %>
          <% end %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li class="">
              <%= link_to edit_user_registration_path do  %>
              <%= image_tag (current_user.avatar(:thumb)) %>
              <% end %>
            </li>
            <li class=""><%= link_to "Grupos", user_groups_path %></li>
            <li class=""><%= link_to "Torneos", leagues_path %></li>
            <li class=""><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
            <% if current_user.admin? %>
              <li class=""><%= link_to "Admin", rails_admin_path %></li>
            <% end %>
          <% else %>
            <li><%= link_to "Entrar", new_user_session_path %></li>
            <li><%= link_to "Registrarse", new_user_registration_path %></li>
          <% end %>
            <!-- <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div growl class="growlMessages"></div>
    <div class="container theme-showcase">

      <%= yield %>

    </div> <!-- /container -->

    <!-- Javascripts -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "yeti" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>